[zh]
  languageName = "中文"
  contentDir = "content"
  weight = 1
  [zh.params]
    languageISO = "zh-CN"
    languageTag = "zh-CN"
    footer = 'Copyright © 2025 by Lipset. All rights reserved.'

[en]
  languageName = "English"
  contentDir = "content"
  weight = 2
  [en.params]
    languageISO = "en-US"
    languageTag = "en-US"
    footer = 'Copyright © 2025 by Lipset. All rights reserved.'
